<?php
/**
 * @file
 * Defines Widget filter.
 */

/**
 * Implements hook_wysiwyg_include_directory().
 */
function wysiwyg_widget_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'plugins':
      return $type;
  }
}

/**
 * Implements hook_filter_info().
 */
function wysiwyg_widget_filter_info() {
  return array(
    'widget_embed' => array(
      'title' => t('Widget embed'),
      'process callback' => '_wysiwyg_widget_embed_filter',
      // Needs to be after any filter that limits html tags.
      'weight' => 50,
    )
  );
}

/**
 * Callback for hook_filter_info().
 */
function _wysiwyg_widget_embed_filter($text, $filter, $format, $langcode, $cache, $cache_id) {
  return preg_replace_callback(
    '|<!--widget_embed:(.*?)-->|si',
    function ($matches) {
      return rawurldecode(($matches[1]));
    },
    $text
  );
}

/**
 * Implements hook_menu().
 */
function wysiwyg_widget_menu() {
  $items = array();

  $items['admin/config/content/wysiwyg_widget'] = array(
    'title' => t('Wysiwyg Widget settings'),
    'description' => t('Configure settings for Wysiwyg Widget.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wysiwyg_widget_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback for Wysiwyg Widget settings form.
 */
function wysiwyg_widget_settings($form, &$form_state) {
  $form = array();
  $form['wysiwyg_widget_xss_header'] = array(
    '#type' => 'checkbox',
    '#title' => t('Send X-XSS-Protection header'),
    '#default_value' => variable_get('wysiwyg_widget_xss_header', 0),
    '#description' => t('When checked, the X-XSS-Protection header will be sent to prevent the "err_blocked_by_xss_auditor" error on Chrome.'),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 *
 * Send X-XSS-Protection header to avoid the "err_blocked_by_xss_auditor"
 * error on Chrome.
 */
function wysiwyg_widget_wysiwyg_editor_settings_alter(&$settings, $context) {
  $set_XSS_header = variable_get('wysiwyg_widget_xss_header', 0);
  // Only send the header when the widget_embed plugin is present.
  if ($set_XSS_header == 1 && strpos($settings['plugins'], 'widget_embed') !== FALSE) {
    drupal_add_http_header('X-XSS-Protection', '0');
  }
}
